# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jorge Estanislao Barsoba
email: jebarsoba@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 "To combine is to create; to engineer, divine".
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jebarsoba.github.io" # the base hostname & protocol for your site
twitter_username: jebarsoba
github_username:  jebarsoba
linkedin_username: jorge-e-barsoba-20344020

# Build settings
markdown: kramdown
